export default {
  translation: {
    titleTwo: "If you don't have an account, please sign up!",
    spanLogin: "Enter your name: ",
    spanEmail: "Enter your e-mail: ",
    firstPassword: "Enter your password: ",
    secondPassword: "Re-enter your password: ",
    spanLang: "What is your language?",
    langOptOne: "**Choose your language**",
    langOptTwo: "Russian",
    langOptThree: "German",
    langOptFour: "English",
    checkboxQuestion: "Do you agree to the terms and conditions?",
    checkboxStatement: "You agree to the terms and conditions.",
    signup: "Sign up",
    login: "your name (use CYRILLIC characters!):",
    email: "your e-mail",
    password: "your password",
    logSub: "Your name: ",
    emailSub: "Your e-mail is: ",
    pOneSub: "Your password is: ",
    pTwoSub: "Is this the same password? ",
    langSubmitted: "Your language is: ",
    confirm: "Click here to sign up!",
    thankyou: "Thank you!",
  },
};
