export default {
  translation: {
    titleTwo: "Зарегистриуйтесь, если у Вас нет учётной записи!",
    spanLogin: "Введите имя и фамилию: ",
    spanEmail: "Введите электронную почту: ",
    firstPassword: "Введите пароль: ",
    secondPassword: "Введите пароль ещё раз: ",
    spanLang: "Выберите язык: ",
    langOptOne: "**Ваш язык**",
    langOptTwo: "Русский",
    langOptThree: "Немецкий",
    langOptFour: "Английский",
    checkboxQuestion: "Вы принимаете условия соглашения?",
    checkboxStatement: "Вы приняли условия соглашения.",
    signup: "Зарегистрироваться",
    login: "Имя и фамилия на кириллице!",
    email: "Ваша электронная почта",
    password: "Ваш пароль",
    logSub: "Ваше имя: ",
    emailSub: "Ваша электронная почта: ",
    pOneSub: "Ваш пароль: ",
    pTwoSub: "Это тот же самый пароль? ",
    langSubmitted: "Ваш язык: ",
    confirm: "Нажмите для регистрации",
    thankyou: "Спасибо!",
  },
};
